### ISSUE TITLE
Doesn't seem compatible with Better Trader

### ISSUE THREAD

**Issue by AmyS1994** [OhhLoz/HoneyPlus#8] opened 2021-05-02 00:38 UTC
[Better Trader](https://www.nexusmods.com/valheim/mods/433) populates its config file with the items in Valheim's ObjectDBCache however it can't seem to find the items from Honey Plus despite HP loading before BT. Are the items added to ObjectDB?

**Comment by OhhLoz** [comment] 2021-05-03 23:19
Hi, 

Sorry for the late response, thanks for your interest in my mod. I will have to look into that further, I would have to assume that occurs due to how ValheimLib populates the ObjectDB, this might be fixed in a future update as ValheimLib has recently merged with JotunnLib so perhaps when its migrated to the newer versions that will work.

**Comment by AmyS1994** [comment] 2021-05-04 00:29
I hadn't considered that it was ValheimLib's fault - that actually explains it! Yours is the only mod I use that adds items (as opposed to building pieces) using VL and it's coincidentally the only one that BT can't figure out. Cheers for that and I hope the merged api helps it

**Comment by OhhLoz** [comment] 2021-06-03 19:20
This might work now with version 2.0.0. I'll try to test it when I can

**Comment by AmyS1994** [comment] 2021-07-30 16:33
Hello I have been Valheimless until now thanks to a dead laptop but I can confirm that the port to Jotunn has made Better Trader work with HoneyPlus now so this issue can be closed!

**Comment by OhhLoz** [comment] 2021-07-30 16:50
Thanks, I dont really play Valheim anymore but I tried using Better Trader and It wasnt working for me.

Thanks for letting me know the issue is fixed!

**Closed by OhhLoz** 2021-07-30 16:50 UTC
